orbitdb/orbitdb

Makefile
This makes it safe it `make` is run with -j X.
It was derp on my side as I had MAKEFLAGS set.
=> Fixup makefile

Makefile, package.json
This PR will add `npm run build:debug` to the default build script resulting in debug (non-minified) build being built by default. The debug build and sourcemaps are copied to the browser examples directory.
Fixes #294
=> Build debug build by default

src/OrbitDB.js, test/create-open.test.js
This PR will add a mapping objet from "database type" -> Class. 
In addition, this PR will add `.databaseTypes` property to OrbitDB class, refactor the internal _createStore() function and remove _openDatabase().
=> Create a mapping for database types

README.md, src/OrbitDB.js, test/create-type.test.js
Add an `.addType(name, store)` method that updates the `databaseTypes` object so that OrbitDB can pre-process them like other store types.
Addresses https://github.com/orbitdb/orbit-db/issues/307
=> Add custom types

package-lock.json, package.json
This PR will update OrbitDB to use the latest local cache module. The updated version of the cache module fixes a bug where databases were don't load the persisted db in the browsers.
Closes #315.
=> Update to latest orbit-db-cache

src/OrbitDB.js, test/custom-keystore.test.js, test/utils/custom-test-keystore.js
This PR adds a check for `keystore` option, this way we can implement our own keystores or reuse it in cases where the app already have that. The keystore should follow `orbit-db-keystore`'s API since `orbit-db-store` and `ipfs-log` depends on it.
Closes #319
=> Allow a custom keystore object to be specified via options

src/orbit-db-access-controllers/orbitdb-access-controller.js
It looks like the keys list in oplog isnt aware of access updates. We should emit an event when changing access capabilities
=> emit update event when changing access rights

test/counterdb.test.js, test/create-open.test.js, test/create-type.test.js, test/drop.test.js
This PR will fix tests where db.stop() is called synchronously. Missing `await` was added where applicable.
=> Wait for database to close in tests

package-lock.json, package.json, src/OrbitDB.js, test/replicate-automatically.test.js
This PR will use ipfs-pubsub-1on1 module to create a direct communication channel between two peers to exchange heads when connected.
- Use ipfs-pubsub-1on1
- Use latest orbit-db-store modules
- Pass onClose callback to stores as per orbit-db-store 2.3.0
=> Use ipfs-pubsub-1on1 to exchange heads between connected peers

package-lock.json, package.json
This PR will update orbit-db-pubsub to the latest version which uses ipfs-pubsub-peer-monitor instead of ipfs-pubsub-room for exchanging heads upon connecting to peers.
=> Use ipfs-pubsub-peer-monitor via latest orbit-db-pubsub

package-lock.json, package.json
This PR will update ipfs-pubsub-1on1 to the latest version (0.0.4) that contains a fix for js-ipfs-api compatibility.
The fix was done in https://github.com/haadcode/ipfs-pubsub-1on1/issues/1.
=> Use latest ipfs-pubsub-1on1

API.md, test/eventlog.test.js, test/feed.test.js
The `gt`/`gte`/`lt`/`lte` options for enventlog and feed iterators take the hash of an item, and that wasn't clear from the API docs. Also added more info to the `limit` option.
To see usage examples, many people are likely to turn to test suite. In the tests for eventlog and feed, the `items` variable first referred to an iterator with the actual items, and then later in the tests `items` was an array of the item hashes. This switch of types can be pretty confusing, thus the variable names were disambiguated.
=> Clarify eventlog and feed iterator options, and usage in tests

README.md, package.json
Instructions for running examples only applied to MacOS. Rather than introducing
a new NPM dependency for running platform-specific commands, I thought it's
simpler to just have own scripts for each platform.
=> Add Linux-specific installation details in README

package-lock.json, package.json, test/docstore.test.js
This PR will pull in the latest document store which adds the feature to get the full operation data with `query()`.
- Updates package.json and the lockfile
- Adds a test to test that the document store returns the full op data
=> Use latest document store

examples/browser/example.js
Changed to _replicationStatus to match tests and latest code and the example works again.
=> _replicationInfo no longer exists and breaks the browser example code.

package-lock.json, package.json, src/OrbitDB.js
Update to latest ipfs packages (`js-ipfs`, `ipfs-repo`, `ipfsd-ctl`) with a fix for [breaking changes to `pubsub.unsubscribe` in js-ipfs-api](https://github.com/ipfs/js-ipfs-api/blob/master/CHANGELOG.md#breaking-changes) which affects `orbit-db-pubsub`.
Also, the latest ipfs is throwing the following warning on tests:
```
WARNING, trying to set config on uninitialized repo, maybe forgot to set "init: true"
```
Follow up to orbitdb/orbit-db#370.
Needs orbitdb/orbit-db-pubsub#12 merged.
=> feat: update ipfs deps + make pubsub.unsubscribe async

package-lock.json, package.json
This PR will change package.json to use latest published orbit-db-pubsub from npm instead of a branch.
=> Use latest orbit-db-pubsub module

package.json, test/replicate.test.js
This PR will pull in the latest orbit-db-store which contains a fix for [caching verified entries only](https://github.com/orbitdb/orbit-db-store/commit/1e3d55d313b8d311dc066e6b34f344e9145d6a57).
Added a try/catch to catch assertion errors in replication tests that weren't caught before.
=> Use latest orbit-db-store

package-lock.json, package.json, test/create-open.test.js
This PR will update dependencies to use the latest orbit-db-cache which brings in LevelDB v3 modules.
Fixes #392.
=> Use latest orbit-db-cache and leveldb modules

package-lock.json, package.json
This PR will update package.json and package-lock to use the latest orbit-db-store (2.5.3) which contains a [fix for clearing replicator](https://github.com/orbitdb/orbit-db-store/pull/29) timers on shutdown.
=> Use orbit-db-store 2.5.3

circle.yml
This PR will remove the obsolete CircleCI 1.0 config file. We updated to 2.0 in https://github.com/orbitdb/orbit-db/pull/404 but I forgot to remove the old file.
=> Remove CircleCI 1.0 config file

src/exchange-heads.js
For ipfs-api, during heavy load when multiple db heads are being exchanged if there is no wait here for the send to complete then the actually publish won't complete and the peers would not receive the heads sent to it. This seems to alleviate the problem, though it's not totally predictable.
=> Wait for send to complete on exchange heads

API.md
Add missing `replicate` config option for `OrbitDB.create()` and `OrbitDB.open()`.
Related #425
=> Document replicate option

README.md
This adds a Gitter badge to our Gitter room at https://gitter.im/orbitdb/Lobby. For more on how we plan to use Gitter in the OrbitDB community, take a look at https://github.com/orbitdb/welcome/issues/28.
=> docs: Add a Gitter badge

docker/Dockerfile, docker/README.md
This PR defines the base image for running OrbitDB code in containers. It's something that I've personally been using for a while, so it can already be used locally for running tests or examples in isolated container. Besides the initial Dockerfile for building OrbitDB base images, there's some instructions how to use it with Docker. 
There is optimization left to do in base image itself to make it leaner (smaller nodejs-base image, multi-stage builds etc). Also I've only been using it on Linux where there are usually no problems with containers, so it'd be great to hear experiences from Docker for Mac/Windows users.
=> Dockerfile for OrbitDB base image

API.md
In the latest docstore code, the docstore.get() function does not use the `fullOp` option to retrieve a document ([code](https://github.com/orbitdb/orbit-db-docstore/blob/master/src/DocumentStore.js#L30)). Therefore, the docstore.get() function should by default return the payload value ([code](https://github.com/orbitdb/orbit-db-docstore/blob/master/src/DocumentIndex.js#L11)) and there is no need to add the secondary mapper function any more.
=> docs(api): fix outdated doc

Makefile
This PR will update the Makefile to keep package-lock.json file on `clean` as per https://github.com/orbitdb/orbit-db/pull/401. 
This PR will also ass `rebuild` command which addresses the concerns I had in #401.
Closes #401.
=> Keep package-lock on make clean, add make rebuild command

CODE_OF_CONDUCT.md, README.md
The Code is already in orbitdb/welcome, but it has not been added to this repository yet. Doing so will mean that it is mentioned when people make PRs, and that it will be more visible to people coming to this repo.
=> docs: Add the Code of Conduct

conf/webpack.config.js, conf/webpack.debug.config.js, conf/webpack.example.config.js, examples/browser/browser.html, examples/browser/example.js, examples/eventlog.js, examples/keyvalue.js, package-lock.json, package.json
This PR will update the examples to use the latest APIs. It'll remove the `lib` folder and copying to it when building examples and rather use the dist builds of each modules directly from `node_modules`.
From the commit message:
- Use new orbitdb API
- Remove usage of lib and use dist builds of each dependency
=> Fix examples

FAQ.md, README.md, package.json
This pull request adds an FAQ document. @haadcode has started opening issues for questions and labelling them as 'FAQ', which I think is a good start. However, I don't think that the questions should stay there. Issues which are open for a long time tend to inflate the issue count, which can negatively affect maintainer guilt around too many open issues, and can be confusing for new contributors who are looking for answers to specific questions and see too many issues with the keywords they're looking for. Having a document doesn't really solve this problem - documents grow stale, too - but I think it makes it easier for people to find the relevant questions, and more importantly it makes it much easier for maintainers to point to a canonical answer instead of answering the same question …
=> Add an FAQ document

CONTRIBUTING.md
This will direct people to the correct document, and flag the guide as something to read when people open a PR or an issue on GitHub.
=> docs: Stub out a Contributing guide

src/OrbitDB.js, test/create-open.test.js
This code adds the ability to pass an identity when you open a DB. This allows you to have multiple DBs open with different identities at the same time.
=> feat: Accept identity as an option when opening a DB

docker/Dockerfile
- Bumped NodeJS version to 10 (container was building but not running any of the examples with the other version)
- Added SSL ignore to fix ssl issues when performing npm install
=> Bumped NodeJS version

docker/Dockerfile
When running the container and building the examples (on Windows 10), the following error occurs:
```
Error: EACCES: permission denied, open '/home/node/examples/browser/browser-webpack-example/bundle.js'
```
Commands used to test this fix:
```
docker build -t orbit-db -f docker/Dockerfile . --no-cache
docker run -ti --rm orbit-db npm run build:examples
```
=> Examples folder default permission

test/create-open.test.js
Fixes:
```
TypeError [ERR_MISSING_ARGS]: The "actual" and "expected" arguments must be specified
at Function.notEqual (assert.js:406:11)
at Context.<anonymous> (test/create-open.test.js:137:18)
```
=> fix: assert value exists

.circleci/config.yml, API.md, conf/webpack.config.js, conf/webpack.debug.config.js, conf/webpack.example.config.js, examples/browser/example.js, package-lock.json, package.json, src/OrbitDB.js, src/db-manifest.js, src/exchange-heads.js, src/orbit-db-address.js, test/counterdb.test.js, test/create-open.test.js, test/custom-cache.test.js, test/custom-keystore.test.js, test/drop.test.js, test/persistency.js, test/replicate-and-load.test.js, test/replicate.test.js, test/set-identity.test.js, test/utils/custom-test-cache.js, test/utils/custom-test-keystore.js, test/v0-open-load.js, test/write-permissions.test.js
This PR implements the [`orbit-db-storage-adapter`](https://github.com/orbitdb/orbit-db-storage-adapter) paradigm which has two main benefits:
1. Greater performance (see benchmarks below)
2. Easier Interop to redis, mongo, sqlite at the cache and keystore level via the storage adapter
Before:
```
$ node benchmarks/benchmark-add.js
Starting IPFS daemon...
95 queries per second, 95 queries in 1 seconds (Oplog: 95)
87 queries per second, 182 queries in 2 seconds (Oplog: 182)
80 queries per second, 262 queries in 3 seconds (Oplog: 262)
88 queries per second, 350 queries in 4 seconds (Oplog: 350)
87 queries per second, 437 queries in 5 seconds (Oplog: 437)
85 queries per second, 522 queries in 6 seconds (Oplog: 522)
83 queries per second, 605 queries in 7 seconds (Oplog: 606)
88 queries per …
```
=> Persistent connection in the keystore

package-lock.json, package.json, src/OrbitDB.js, src/fs-shim.js, src/migrations/0.21-0.22.js
This PR removes `leveldown` as a direct dependency, instead relying on the implementation of `level` in `orbit-db-storage-adapter`, which in turn handles browser vs node dependency switching.
In addition, it utilizes a neat trick that uses eval to require the `fs` module, ensuring webpack compilation while still allowing node to use `fs`
=> Ensure webpack compiles in downstream projects

src/OrbitDB.js, src/db-manifest.js, test/create-open.test.js
This PR would give users the ability to add additional data to the db manifest. This could be useful when wanting to package information with the db that should not change during the lifetime of the db. An example could be adding a public ECDH key that the owner of the db controls.
The meta field would only exist in the manifest if `options.meta !== undefined` is true when creating the database. This keeps db addresses the same as before when creating a db without a meta field. When creating a db with a meta field, make options.meta equal to a JSON serialize-able value so it can safely traverse to/from ipfs. This value with be readable in the db instance property db.options.meta (if the manifest does not contain a meta field db.options.meta is undefined).
The tests added will check when …
=> adds optional meta field to manifest

package.json
`ipfs@0.38.0` has shipped so no need to depend on the release candidate any more.
=> Upgrade to non-rc IPFS

src/OrbitDB.js
so we can grab them from OrbitDB without reimporting them.
Related to https://github.com/orbitdb/orbit-db/issues/715
=> Expose modules in OrbitDB object

src/OrbitDB.js, test/create-type.test.js
Currently it's possible to open a db via an address with a different path component then what the original manifest name was set to. This Pr prevents the issue by throwing an error is such a mismatch occurs.
=> Error if address path mismatches manifest name

test/persistency.js
This PR will catch an unhandled (but expected) error in one of the tests. 
Before, the error was seen in the test output. After this PR, the error is not shown in the output (expected).
=> Catch unhandled error in test

API.md, src/OrbitDB.js, test/offline-mode.js
This PR adds an options flag to start an OrbitDB instance in offline mode. 
Inside OrbitDB, if `options.offline: true` is set, Pubsub won't be started, thus no exchange of updates will happen.
This is a useful feature for example when starting IPFS nodes offline (with `new IPFS({start: false})`). For example, we should optimize some of the tests to use offline IPFS and OrbitDB nodes for faster startup times and to decrease overall testing time.
The flag is documented as:
- `offline` (boolean): Start the OrbitDB instance in offline mode. Databases are not be replicated when the instance is started in offline mode. If the OrbitDB instance was started offline mode and you want to start replicating databases, the OrbitDB instance needs to be re-created. Default: `false`.
And would be used …
=> Add offline mode

benchmarks/benchmark-load.js
This PR adds a program to benchmark db loading times.
Run with:
```
node benchmarks/benchmark-load.js
```
Output:
```
Starting IPFS...
DB entries: 1000
Writing DB...
writing took 1745 ms
Loading DB...
load took 678 ms
```
=> Add a benchmark for loading a db

src/orbit-db-address.js
Re https://github.com/orbitdb/orbit-db-http-api/issues/23 
On some occasions an ipfs address can start with `ba`
```
ipfs dag get bafyreicjqmfea2dlhcbyszyneaxcpdhlxjpsycxxaibpp4wlzfctiujxdm
{"accessController":"/ipfs/zdpuAzt2GWKYeF4Pbo3hcMipCimE7SqCKZcckGduqcDJ3tmRx","name":"docstore","type":"docstore"}
ipfs cid format -f "%P" bafyreicjqmfea2dlhcbyszyneaxcpdhlxjpsycxxaibpp4wlzfctiujxdm
cidv1-cbor-sha2-256-32
```
=> Allow hashes to begining with 'ba'

test/create-open.test.js
Fixes the following errors:
```
2) orbit-db - Create & Open (js-ipfs)
Create
Success
saves database manifest file locally:
TypeError [ERR_MISSING_ARGS]: The "actual" and "expected" arguments must be specified
at Function.notEqual (assert.js:418:11)
at Context.<anonymous> (test/create-open.test.js:145:18)
3) orbit-db - Create & Open (go-ipfs)
Create
Success
saves database manifest file locally:
TypeError [ERR_MISSING_ARGS]: The "actual" and "expected" arguments must be specified
at Function.notEqual (assert.js:418:11)
at Context.<anonymous> (test/create-open.test.js:145:18)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
=> Fix assert.notEqual

README.md, package-lock.json, package.json
This PR ensures orbit-db remains compatible with HTTP API exposed by go-ipfs 0.5 (https://github.com/ipfs/go-ipfs/issues/7109) by switching to `ipfs-http-client@41.0.1` in tests and adding interop note in README.  
- **added interop note to README about compatible http client version**
- note about version limitation can be removed when #767 lands
- bumped versions of http-client and go-ipfs used in tests to ensure it works with latest go-ipfs 0.5.0-rc2
go-ipfs 0.5  will block `GET` commands on the API port (https://github.com/ipfs/go-ipfs/pull/7097), requiring every  command (RPC) to be sent as HTTP `POST` request.
Why v41.0.1? It sends only POST requests while maintaining the old JS API 
(breaking changes that introduced support for async iterators landed in 42.x)
cc @aphelionz …
=> fix: support POST-only API of go-ipfs 0.5

package-lock.json, src/OrbitDB.js, test/re-exports.test.js
This PR adds `AccessControllers`, `Identities`, and `Keystore` as re-exports from OrbitDB, so you can do:
```javascript
const { AccessControllers, Identities, Keystore } = require('orbit-db')
```
=> feat: adding AccessControllers and Identites re-exports

src/fs-shim.js
The fs shim does not work properly when used inside an [electron renderer process](https://www.electronjs.org/docs/tutorial/application-architecture#main-and-renderer-processes), where both native node modules and chromium (i.e. global `window`) are available. This is one simple way to address the issue.
=> fix: fs shim when running inside electron renderer process

package.json
=> chore: update go-ipfs to 0.5.1

package.json
The `js-ipfs` distribution file is now named index.min.js instead of index.js. rename the `cpy` instruction source in the test script definition
=> Fix broken browser tests

src/orbit-db-address.js
The 0.6.0 version of go-ipfs introduces base36 cids, so It'd be good if we can get ahead of any issues that might occur when (if) this becomes the default and support it right out of the gate. The logic with the existing single if statement was rapidly getting out of hand and foreseeably was going to get worse over time given the amount of format changes cids are undergoing,; So it required a small refactor to make it neater & easier to add new cases.
e.g. base36 cid `k51qzi5uqu5dj16qyiq0tajolkojyl9qdkr254920wxv7ghtuwcz593tp69z9m`
=> Suport new base36 format, Improve unwieldy logic

.circleci/config.yml, Makefile, package-lock.json, package.json, src/exchange-heads.js, test/counterdb.test.js, test/create-open.test.js, test/create-type.test.js, test/custom-cache.test.js, test/custom-keystore.test.js, test/docstore.test.js, test/drop.test.js, test/eventlog.test.js, test/feed-load.test.js, test/feed.test.js, test/kvstore.test.js, test/multiple-databases.test.js, test/offline-mode.js, test/orbit-db-address.test.js, test/persistency.js, test/replicate-and-load.test.js, test/replicate-automatically.test.js, test/replicate.test.js, test/replication-status.test.js, test/set-identity.test.js, test/write-permissions.test.js
=> Updating for js-ipfs 0.50 and go-ipfs 0.6.0

README.md
We no longer hold these regularly. Happy to have them again, but it seems disingenuous to keep them in this doc.
=> docs: Remove sections about community calls.

README.md
This pr changes the logo file used in README.md 
from 
`images/orbit_db_logo_color.jpg`
to
`images/orbit_db_logo_color.png`
Both files existed previously.
The purpose of this pr is to play nicer with the new Dark Theme [appearance](https://github.com/settings/appearance).
@aphelionz brought this issue/improvement up in the community chat.
Test out how it looks in the branches preview
https://github.com/tabcat/orbit-db/tree/png-logo
=> use png logo for readme

README.md
updates the demo link for example-orbit-db-todomvc to the latest
related: https://github.com/orbitdb/example-orbitdb-todomvc/pull/17
=> update todomvc ipfs link

API.md
If a key does not exist in a  `docs` Store, the  `DocumentStore.get` method returns an empty array.
I made a notice of this in the Documentation of `DocumentStore.get`.
But this is perhaps not all, that can be done here.
Are there other possible scenarios with `DocumentStore.get` that should 
also be noted in the Documentation?
=> Added notice of an edge case

API.md
The documentation starts with a statement describing all the possible cases and then describes the edge case of no document matching a key.
=> Specified all possible intended behaviors of `DocumentStore.get`

src/OrbitDB.js
To make it possible to access the class from the main module,
without the use of another module.
Like the other stores have already been made available.
=> Add `OrbitDB.Store` property

API.md
The order of `oplog.values` is not explicitly defined.
=> Documentation of the ordering in oplog.values

package-lock.json, package.json, src/fs-shim.js
is-electron returns true for the electron renderer process, which leads to a `require is not defined` error. Using wherearewe instead and explicitly checking for the electron main process resolves this issue.
=> Fix fs-shim error in electron renderer process

README.md, examples/browser/browser.html
1.  corrected reference to ipfs.js
2.  corrected build instructions so browser libs are correctly copied
3.  added workaround to README in case browser isn't opening (under MacOS)
=> wrong ipfs.js reference in browser examples 

src/OrbitDB.js
Two improvements to the style of the OrbitDB.disconnect function:
- it uses both forEach and for loops to close connections. I removed the one instance of using forEach and replaced it by using a for loop.
- it repeatedly deletes every element in an object using `delete`. I removed these and reassigned the variable to an empty object at the end of the loop. I believe this would be more efficient, because garbage collectors do not have to reallocate the object piece meal.
=> Small: cleaned up code in disconnect

src/OrbitDB.js
While creating an instance with:
```javascript
import { create } from 'ipfs-core'
import OrbitDB from 'orbit-db'
create({
repo: './orbitdb/pinner',
start: true,
EXPERIMENTAL: {
ipnsPubsub: true
},
config: {}
}).then((ipfs) => {
OrbitDB.createInstance(ipfs,
{directory:'.'
})
.then((db) => {
console.log(db.id)
})
})
````
I get this error:
```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Ed25519PeerIdImpl
at new NodeError (node:internal/errors:372:5)
at validateString (node:internal/validators:120:11)
at Object.join (node:path:1172:7)
at Function.createInstance (/Users/ME/Development/orbitdb-server/node_modules/orbit-db/src/OrbitDB.js:109:33) {
code: 'ERR_INVALID_ARG_TYPE'
```
This is my workaround:
```javascript
typeof id !== …
```
=> ipfs.id() is not a string

.github/workflows/run-test.yml
This PR adds a Github Actions script to run the tests (`npm test`) on every push to all branches.
Once all working properly, this will make CircleCI obsolete.
=> Add a Github Action config for running tests on all branches on push

.github/workflows/npm-publish-next.yml
This PR adds a command to run the linter when publishing the "next" tag version to npm.
=> Run linter on publishing next version

src/orbitdb.js, test/orbitdb-open.test.js
This PR fixes a bug where opening a database with name would error and not return the cached instance.
=> Fix db instance caching

src/orbitdb.js, test/orbitdb-open.test.js
This PR fixes a bug where calling `orbitdb.stop()` doesn't close the open databases and upon restarting orbitdb, trying to open a database that was previously open throws an error.
=> Close databases when orbitdb is stopped

README.md
When copy & pasting the example code it never worked the first time. Now it does.
=> missing async caused confusion

benchmarks/orbitdb-replicate.js, src/oplog/entry.js, src/oplog/heads.js, src/oplog/log.js, test/oplog/join.test.js, test/orbitdb-replication.test.js
This PR introduces a new implementation of the Oplog's `joinEntry` function.
The implementation changes the way entries are joined by 1) traversing the missing entries between the entry-to-be-joined and current heads or entries in the log and 2) verifies each new entry as they are traversed. This is more efficient than the previous implementation and adds to the security by making sure all entries are verified before adding them to the (local) oplog.
Added a bunch of tests to cover the various forking/joining cases, exposed `Entry.decode()` for testing purposes and added `Heads.remove()` to remove heads one by one used in the new implementation.
Fixes #1110.
=> Improve Oplog's joinEntry implementation

test/utils/create-helia.js
This PR removes the default `[trustlessGateway](https://github.com/ipfs/helia/blob/299bb0942bbfae492db938c4ccad4e835bab2dbd/packages/helia/src/helia.ts#L49)` used in helia and changes the configuration to use `bitswap` instead.
Doing so removes various calls to the gateway urls in tests.
=> Use only bitswap in tests

benchmarks/orbitdb-documents.js
This PR adds a simple benchmark script for the Documents database.
It measures write throughput and query throughput in `ops/s` (operations per second) and `ms/op` (milliseconds per operation).
The benchmark is run with `node benchmarks/orbitdb-documents.js` and the output looks like this:
```
Starting benchmark...
Insert 1000 documents
Inserting 1000 documents took 2278 ms, 438 ops/s, 2.278 ms/op
Query 1000 documents
Querying 1000 documents took 81 ms, 12345 ops/s, 0.081 ms/op
```
=> Add a benchmark for Documents database

src/oplog/entry.js, src/oplog/log.js
This PR improves the overall query performance for all databases.
The improvements come from two changes to the Oplog.
1) Remove an unnecessary entry encoding step
In Entry's `decode()` function we had it so that we encoded the entry once the serialized block was decoded. This was unnecessary and by removing this step we gain a significant write and read performance improvement. From:
```
Starting benchmark...
Insert 1000 documents
Inserting 1000 documents took 1642 ms, 609 ops/s, 1.642 ms/op
Query 1000 documents
Querying 1000 documents took 72 ms, 13888 ops/s, 0.072 ms/op
```
To:
```
Starting benchmark...
Insert 1000 documents
Inserting 1000 documents took 1284 ms, 778 ops/s, 1.284 ms/op
Query 1000 documents
Querying 1000 documents took 52 ms, 19230 ops/s, 0.052 ms/op
```
2) Remove …
=> Improve Oplog performance

README.md, docs/GETTING_STARTED.md, package-lock.json, package.json, test/utils/create-helia.js
Update gossipsub options in line with [release notes](https://github.com/ChainSafe/js-libp2p-gossipsub/releases).
The OrbitDB examples, tests and documentation will refer to the latest version of GossipSub. OrbitDB instances implementing older versions of GossipSub will not work with these examples.
=> chore: Iterate gossipsub. Changes to gossipsub options.

docs/DATABASES.md, docs/REPLICATION.md, src/sync.js
- fixes links to https://api.orbitdb.org/module-Sync.html
- fixes formatting of sync module docstring
=> Docs: Fix links & docstring formatting

README.md
- It doesn't render in code IDE after downloading code source.
- So, I issues this pr, and fix it.
=> docs: add code identifier to wrap <script> for markdown rendering

docs/DATABASES.md, docs/GETTING_STARTED.md
When following the Getting Started guide, this npm scoped install did not work, therefore corrected it in sync with the standalone installation guide
`npm i helia @orbitdb/core blockstore-level @chainsafe/libp2p-gossipsub`
=> Consistent package naming for standalone and replicating db guide

test/utils/relay.js
The current relay example specifies custom `reservationTtl` and other settings for `CircuitRelayServer`. However, recent versions of the library include more generous default settings.
With the current configuration, reservations are dropped too quickly by the relay due to a `ttl` set to 1000ms (1 second), while the default is now 2 hours.
This PR updates the example to use the default `CircuitRelayServer` settings, simplifying the configuration:
```js
relay: circuitRelayServer()
```
This change is related to an issue I encountered while testing browser to browser replication. You can find more details in the issue reported [here](https://github.com/haydenyoung/orbitdb-browser-example/issues/1).
If preferred, I can adjust the PR to only change the reservationTtl value and keep the rest of …
=> fix: Update relay example to use default reservation ttl setting

src/sync.js
Fix for the change in libp2p here: https://github.com/libp2p/js-libp2p/pull/2655
=> Use `.name` instead of `.code` for errors
