orbitdb/orbitdb

- examples/benchmark.js
- examples/browser.js
- package.json
- src/OrbitDB.js
Needs https://github.com/haadcode/ipfs-log/pull/5
> use js-ipfs

- package.json
- src/OrbitDB.js
- test/client.test.js
DocumentStore to retrieve docs by string contained in title
closes #56
> Add DocumentStore

- README.md
> Add note about IRC and twitter

- API.md
Added the documentation as mentioned in Issue #230 .
Please suggest if anything more is required to add in the PR.
> Documentation for options added

- .gitignore
- .npmignore
Clean up what gets tracked in git and what gets distributed in the npm package
> Clean up npm package and git repo directory structures

- README.md
> Fixing broken link for orbit-db-demo-3.gif

- conf/webpack.debug.config.js
* changes debug config to include source maps
> add source maps for debug build

- CHANGELOG.md
This PR will update CHANGELOG.md for v0.19.0
This release bring a bunch of fixes and updates improving performance, stability and browser compatibility. As always, we highly encourage to update to the latest version and report any problems in https://github.com/orbitdb/orbit-db/issues.
A big thank you to all the contributors who helped and contributed to this release! <3
The previous release included a refactored version of the replication code and we've improved it even further in this release in terms of performance as well as stability. We're now seeing *huge* improvement in replication speed, especially when replicating a database from scratch.
To observe these improvements, run the [browser examples](https://github.com/orbitdb/orbit-db/tree/master/examples/browser) with two …
> Changelog for v0.19.0 release

- package-lock.json
- package.json
- test/persistency.js
- test/replicate.test.js
This PR will fix the "segmentation fault" error we're sometimes seeing in the tests.
> Fix segmentation fault

- package-lock.json
- package.json
This PR will update js-ipfs module to v0.28.0
> Use js-ipfs 0.28.0

- package-lock.json
- package.json
- src/OrbitDB.js
- src/exchange-heads.js
- test/multiple-databases.test.js
- test/replicate.test.js
This PR will move the logic of exchanging heads and creating direct channels between peers into its own function.
> Move exchanging heads logic to its own function

- package-lock.json
- package.json
***Work in progress!***
This PR will update package.json to use the latest orbit-db-docstore.
> Use latest orbit-db-docstore module

- README.md
This should close #394, as we have moved the calls issues to that repository.
> docs: Add note about community calls

- README.md
This adds sponsors to the sponsor list.
> docs(README.md): Add Haja and Maintainer sponsors

- src/OrbitDB.js
This PR will refactor the code in OrbitDB.js for checking the locally saved data.
All I did was move the check into its own function which returns `true|false` depending if we have the db data locally.
The motivation for this PR is to clean up the code a little bit, extract common functionality to functions and to use await instead of .then across the code base.
> Refactor checking local db data at open/create

- README.md
In [at least this comment](https://github.com/orbitdb/orbit-db/issues/509#issuecomment-442710847), it was not clear that there were calls. This might help. What do you think?
> docs(README.md): Add note about calls above fold

- conf/webpack.example.config.js
- package-lock.json
- package.json
This is a PR to #495 to remove Uglify completely as it's not used anymore.
> Remove Uglify as obsolete

- README.md
See https://github.com/orbitdb/ipfs-log/pull/216
> Update README.md to include node.js LTS preference

- README.md
> docs: remove freenode

- README.md
> docs: Reference the contributing guide

- README.md
> docs: remove await outside of an async function in example

- test/replicate.test.js
> Remove wrong assertions in replication progress check

- FAQ.md
- README.md
This should make it more accessible.
> docs: Add FAQ section to README

- FAQ.md
See https://github.com/orbitdb/orbit-db/issues/560.
> Add note about preloading data

- FAQ.md
Taken from @aphelionz on Gitter.
> docs: Add question on encryption

- API.md
- GUIDE.md
- README.md
This PR pulls in the docs from https://github.com/orbitdb/orbit-db/pull/566 for the 0.20.0 code.
> Update documentation for 0.20.0

- README.md
This PR will update the code example in README to use `await` instead of `then`.
> Change the readme example code to use await

- package-lock.json
- src/OrbitDB.js
- test/create-open.test.js
Passes the db-name to access-controller creator
> pass dbName to ac

- README.md
> docs: Add await comment

- package-lock.json
- test/v0-open-load.js
> set skipManifest in test

- test/v0-open-load.js
> fix v0-load test

- GUIDE.md
Fixed await operator outside of async function.
> Fixed example code in Guide.md

- package-lock.json
- test/set-identity.test.js
> Add set identity tests

- conf/webpack.config.js
- conf/webpack.debug.config.js
- conf/webpack.example.config.js
- src/OrbitDB.js
- src/db-manifest.js
- src/exchange-heads.js
- src/orbit-db-address.js
This reverts commit 4226921b22d2b5a4d5c391a6dbf0024ff198aafc.
> Applying lint fixes

- src/OrbitDB.js
Depends on https://github.com/orbitdb/orbit-db-store/pull/75
Simplifies `onClose` and `requestCache`
> Use store.options.directory

- GUIDE.md
Fix for [#686](https://github.com/orbitdb/orbit-db/issues/686)
> fix custom access controller example

- README.md
> add bridged chats

- API.md
- GUIDE.md
Updates outdated `API.md` and `GUIDE.md`
> WIP update docs

- test/feed-load.test.js
These tests create a feed and add 10 records to it. Then it tries to call load() with various amounts that are greater than 10.
> Unit tests that verify calling load() on a feed with an amount greater than the number of items loads all the items

- CHANGELOG.md
Updates chagelog v0.22.0
supersedes #699
> update changelog v0.22.0

- API.md
responding to #628  I added the database types to the API.md file
> Docs improvements

- README.md
Adds link to field-manual in usage section of readme
> add field-manual to readme

- FAQ.md
> docs: Adding question on DIDs and access-controls

- FAQ.md
Reverts orbitdb/orbit-db#716
I'm not happy with the way I answered this question. Going to be revisiting it.
> Revert "docs: Adding question on DIDs and access-controls"

- FAQ.md
> docs(FAQ.md): Add question about multiwriter capability

- README.md
These may help people know where to go in the future to learn more.
> docs(README.md): Add links to the Field Manual and Workshop

- README.md
Fixes link to field-manual in readme
> Fix field-manual url

- package-lock.json
- src/OrbitDB.js
- test/offline-mode.js
Requires passing `id` when in offline mode
> use options.id

- CHANGELOG.md
I think this is the best place to put it. Minor changes can be breaking changes in 0.1.0+ releases. We should probably release an alpha at some point, but the whole decentralized stack is bleeding edge, so I think it is OK.
> Add note about Semver

- README.md
Am I blanking on another implementation?
> docs: Add a link to the Golang repo on the README

- CHANGELOG.md
> update changelog v0.23.0

- CHANGELOG.md
We got big improvments to write and load times :tada: 
This PR adds some benchmark results to release notes
> add benchmark results to release notes

- CHANGELOG.md
Add `pin` flag info to release notes
> pin option info

- API.md
Fixes 'write' event docs
closes #584
> fix 'write' event documentation

- src/exchange-heads.js
Implements https://github.com/orbitdb/orbit-db/issues/752
Also partly resolves this fix pr i wrote earlier, with this implementation heads will not longer be [ ] if log is not ready at time of onpeer, and they can still be shared on connecting (instead of waiting)
https://github.com/orbitdb/orbit-db/pull/688
> feat: share heads from cache on peer connect, available before log ready

- README.md
fixed initialization snippet for `ipfs` module (according to current `ipfs` version: "0.41.2")
> fix: fix documentation

- FAQ.md
This PR updates the FAQ answer on pinning to more accurately reflect the current status
> Updating pinning FAQ

- GUIDE.md
creates a field in the guide doc that is very similar to what is on the main readme of the repo
test it out here: https://github.com/tabcat/orbit-db/blob/patch-1/GUIDE.md#api
> add API to GUIDE.md

- API.md
This documents the meta option available at db creation. Includes input type expected, the default for the option, and a description of what it does/affects.
Looking for feedback on wording especially.
> add meta option to doc

- src/fs-shim.js
patch for fs shim electron check.
> fix: fs shim electron check

- README.md
Closes #781 
Repo: https://github.com/orbitdb/orbit-db-control-center
> Add DB explorer UI

- conf/webpack.config.js
- conf/webpack.example.config.js
- src/OrbitDB.js
This PR brought to you by `standard --fix`
> Standard fixes

- GUIDE.md
I updated the examples in the GUIDE.md.
I modified the constructor of the IPFS object. I checked all the examples, they
seem to be working.
This comes from this issue https://github.com/orbitdb/orbit-db/issues/846, 
where I was told that the documentation needed to be updated. 
I hope it helps
Edit from @aphelionz: fixes #847 and fixes #846
> update GUIDE.md according to new constructor of IPFS object

- package.json
This implements changes related to publishing mentioned in https://github.com/orbitdb/orbit-db/issues/852
fixes #852
> fix: dist publish

- README.md
this was resulting in unstaged changes after running `npm run build`
> markdown-toc updates README toc

- README.md
related to https://github.com/orbitdb/example-orbitdb-todomvc/pull/11
> update todomvc link

- README.md
updates the todomvc example link again and to working example
related:
- https://github.com/orbitdb/orbit-db/issues/876
- https://github.com/orbitdb/example-orbitdb-todomvc/pull/20
> point to working todomvc example

- API.md
The options describe how the default behavior is changed,
but it is not specified, what the default behavior is.
Described default behaviour as:
- Chronological
- From earliest to last
> Specified default behavior of iterator.

- GUIDE.md
I think for newbies this is useful information
> added a bit more detailed info on how to get database manifest

- API.md
Documentation for `oplog.values` with examples and some description of the values I found documentation for.
> Detailed documentation of the oplog entries.

- .circleci/config.yml
- package-lock.json
- package.json
> upgrade ipfs-pubsub-1on1

- .github/workflows/run-test.yml
This PR changes the CI action to run tests to force dependency resolving
> Change Github Action to run all tests to force dependency resolving

- .github/workflows/run-test.yml
Remove unnecessary option, add linter
> Fix CI test run script

- API.md
- CHANGELOG.md
- GUIDE.md
- README.md
- package.json
This PR adds release notes (changelog) for the next release, v0.29.0.
The PR also updates the relevant documentation in the project (README, GUIDE, API).
> Release Notes for v0.29.0

- conf/webpack.debug.config.js
This PR fixes the debug build output filename which conflicts with the minimized distribution build filename.
> Rename debug build output file

- FAQ.md
- GUIDE.md
> Fix: typos

- README.md
This PR adds links to relevant projects in readme.
> Add links to readme

- benchmarks/log-iterator.js
- benchmarks/orbitdb-events.js
- benchmarks/orbitdb-replicate.js
This PR fixes the nodejs benchmarks. It also adds a new benchmark for orbitdb-events database.
> Fix nodejs benchmarks

- src/oplog/log.js
> fix log.js iterator

- test/databases/documents.test.js
This PR adds tests for (some of the common) supported data types for documents db documents.
> Add tests for supported data types in documents db

- src/config/libp2p/index.js
- src/sync.js
- test/database.test.js
- test/databases/documents.test.js
- test/databases/events.test.js
- test/databases/keyvalue-indexed.js
- test/databases/keyvalue.test.js
- test/manifest-store.test.js
- test/orbitdb-custom-database-types.test.js
- test/orbitdb-custom-identity-providers.test.js
- test/orbitdb-drop.test.js
- test/orbitdb.test.js
- test/storage.test.js
- test/sync.test.js
- test/utils/connect-nodes.js
This PR removes an obosolete timeout in `connnect-nodes` test utility, fixes couple of types in tests and cleans up code.
> Fix tests and clean up

- README.md
Prevent Error: PublishError.InsufficientPeers when starting alone
> Error: PublishError.InsufficientPeers

- src/storage/composed.js
- test/storage.test.js
This PR will add `del()` function to ComposedStorage, adds tests to test the interfaces of each storage and adds tests for LevelStorage.
> Fix storage

- src/oplog/log.js
This PR fixes race conditions in the oplog when appending or joining entries in rapid succession.
The PR puts each append or join call into a queue which then gets processed in the correct call-order.
> Process appends and joins through a queue

- benchmarks/orbitdb-kv-indexed.js
- src/databases/keyvalue-indexed.js
- src/storage/composed.js
- src/storage/level.js
- test/databases/keyvalue-indexed.js
- test/databases/replication/keyvalue-indexed.test.js
- test/orbitdb-open.test.js
This PR fixes the indexing in KeyValueIndexed database.
> Fix indexing in KeyValueIndexed database

- src/key-store.js
This PR adds a LRU cache to key-store.
The cache contains unmarshalled private keys that then get returned quickly from the cache when the key store is queried for a key. This means that the private key stored in the persistent storage as bytes doesn't have to be unmarshalled on every `get()` request thus improving the performance across databases.
In practice, here's a simple, reduced example how the performance improves with this change:
Before:
```
Inserting 1000 documents took 2278 ms, 438 ops/s, 2.278 ms/op
Querying 1000 documents took 81 ms, 12345 ops/s, 0.081 ms/op
```
After:
```
Inserting 1000 documents took 1642 ms, 609 ops/s, 1.642 ms/op
Querying 1000 documents took 72 ms, 13888 ops/s, 0.072 ms/op
```
> Cache keys in key-store

- docs/GETTING_STARTED.md
Adding changes to the Getting_Started guide in the docs. Fixing Step 2 not working and added new instructions for it.
> Updated GETTING_STARTED.md with new instructions

- src/databases/keyvalue-indexed.js
Just a typo I found when I was reading the source code.
> typo: change shoudStopTraverse to shouldStopTraverse
